version: '3.7'

services:

  seafile:
    image: seafile/seafile:6.3.4
    build: .
    environment:
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - MYSQL_SERVER=mysql-seafile
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SEAFILE_ADMIN=${SEAFILE_ADMIN}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
      - REVERSE_PROXY_MODE=${REVERSE_PROXY_MODE}
    volumes:
      - ./data/seafile:/seafile
    restart: always
    depends_on:
      - mysql-seafile
      #- memcached-seafile
    networks: 
      seafile-network:

  mysql-seafile:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
    volumes:
      - mysql-vol-1:/var/lib/mysql
    restart: always
    networks:
      seafile-network:
        aliases:
          - mysql

  nginx-seafile:
    image: nginx:mainline-alpine
    volumes:
      - ./data/conf/nginx:/etc/nginx/conf.d
      - ./data/seafile:/var/www/seafile
    restart: always
    depends_on:
      - seafile
    networks:
      seafile-network:
        aliases:
          - nginx
      proxy-network:

  #memcached-seafile:
  #  image: memcached:alpine
  #  restart: always
  #  networks:
  #    seafile-network:
  #      aliases:
  #        - memcached

networks:
  seafile-network:
    name: seafile-network
    internal: true
  proxy-network:
    external: true

volumes:
  mysql-vol-1:
